version: '3.8'

volumes:
  prometheus-data: {}
  grafana-data: {}

services:
  # node_exporter:
  #   image: quay.io/prometheus/node-exporter:latest
  #   container_name: node_exporter
  #   command:
  #     - '--path.rootfs=/host'
  #   network_mode: host
  #   pid: host
  #   restart: unless-stopped
  #   volumes:
  #     - '/:/host:ro,rslave'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - '9090:9090'
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana

  my-node-exporter:
    build:
      context: ./../09/.

    container_name: my-node-exporter
    network_mode: host
    pid: host
    volumes:
      - '/:/host:ro,rslave'
    command:
      - '/bin/sh'
      - '-c'
      - |
        /data/entrypoint.sh --path.rootfs=/host

    restart: unless-stopped
