global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['192.168.0.104:9100']

  - job_name: 'nginx-metrics'
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.0.104:9200']
